export enum SocketEvents {
    ISAPI_STORE_EMPLOYEE = 'ISAPI_STORE_EMPLOYEE',
    ISAPI_REGISTER_FINGERPRINT_EMPLOYEE = 'ISAPI_REGISTER_FINGERPRINT_EMPLOYEE',
    ISAPI_DELETE_EMPLOYEE = 'ISAPI_DELETE_EMPLOYEE',
    ISAPI_UPDATE_EMPLOYEE = 'ISAPI_UPDATE_EMPLOYEE',
}
