export enum Tables {
    users = 'users',
    locations = 'locations',
    roles = 'roles',
    activityLog = 'activity_log',
    members = 'members',
    ministry = 'ministries',
    position = 'positions',
    incomes = 'incomes',
    incomeType = 'income_types',
    paymentMethod = 'payment_methods',
    files = 'files',
    // otros sin uso
    biometricDevices = 'biometric_devices',
    departments = 'departments',
    offices = 'offices',
    schedules = 'schedules',
    shifts = 'shifts',
    shiftRules = 'shift_rules',
    employees = 'employees',
    attendances = 'attendances',
    invalidAttendances = 'invalid_attendances',
}
